/**
 * Shared building blocks for the self-contained HTML dashboards (v2).
 *
 * Output contract: one standalone .html file — no external assets, no CDNs,
 * no webfonts. All CSS is inline and all charts are inline SVG, so the report
 * works offline and as a CI artifact. v2 adds ONE inline <script> of fixed,
 * hand-written enhancement code (allowed by the CSP via script-src
 * 'unsafe-inline'); the static markup stays fully readable with JS disabled.
 *
 * Security rules that must never regress — this is a trust layer:
 * 1. Every piece of user data rendered into markup goes through esc().
 * 2. User data reaches JavaScript ONLY through the #mdsc-data JSON blob,
 *    serialized with every '<' escaped as its JSON unicode escape, so a
 *    corrupted datum can never close the script tag. Never interpolate data
 *    into JS source.
 * 3. The enhancement script builds tooltip content with textContent only —
 *    data from the blob must never become markup via innerHTML.
 * 4. The payload deliberately excludes free-text fields that may carry URLs
 *    (explanations, references): the self-containment invariant "http(s)
 *    only inside hrefs" must hold over the whole file.
 */

import { createRequire } from 'node:module'

import type { Finding, QualityDimension, Severity } from '../types'
import { SEVERITY_PENALTY } from '../../scoring/score'

/**
 * Tool version stamped on reports, read from package.json (no drift).
 * The relative path differs between source (src/report/html/) and bundle
 * (dist/), so all candidates are tried.
 */
function resolveVersion(): string {
  const require = createRequire(import.meta.url)
  for (const candidate of ['../package.json', '../../package.json', '../../../package.json']) {
    try {
      return (require(candidate) as { version: string }).version
    } catch {
      // try the next candidate
    }
  }
  return 'dev'
}
export const MDSC_VERSION: string = resolveVersion()

/** Canonical project link, shown in every report header. */
export const REPO_URL = 'https://github.com/pacocartones/market-data-sanity-checker'

/**
 * v2 CSP: inline JS is now allowed (our own fixed enhancement script), but
 * everything else stays locked down — no network, no images, no fonts.
 */
export const CSP = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'"

export const COLORS = {
  critical: '#f85149',
  warning: '#d29922',
  info: '#58a6ff',
  ok: '#3fb950',
  suspicious: '#f0883e',
} as const

export const SEVERITY_RANK: Record<Severity, number> = { info: 1, warning: 2, critical: 3 }

export const FOOTER =
  '<footer>Generated by market-data-sanity-checker · flag, don\'t delete — this tool never rewrites your data.</footer>'

/** HTML-escape any value, safe for text and attribute contexts. */
export function esc(value: unknown): string {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

/** Round to 2 decimals for compact SVG coordinates. */
export function r2(n: number): number {
  return Math.round(n * 100) / 100
}

function clampScore(score: number): number {
  if (!Number.isFinite(score)) return 0
  return Math.min(100, Math.max(0, score))
}

interface ScoreBand {
  label: string
  color: string
}

function scoreBand(score: number): ScoreBand {
  if (score >= 90) return { label: 'reliable', color: COLORS.ok }
  if (score >= 70) return { label: 'usable with caution', color: COLORS.warning }
  if (score >= 40) return { label: 'suspicious', color: COLORS.suspicious }
  return { label: 'not fit for production', color: COLORS.critical }
}

/** Semicircle gauge 0–100, colored by score band. Pure SVG, no JS. */
export function renderGauge(score: number, label: string): string {
  const value = clampScore(score)
  const band = scoreBand(value)
  const radius = 80
  const arcLength = Math.PI * radius
  const filled = (value / 100) * arcLength
  const arc = 'M 20 100 A 80 80 0 0 1 180 100'
  const valuePath =
    filled > 0
      ? `<path d="${arc}" fill="none" stroke="${band.color}" stroke-width="14" stroke-linecap="round" stroke-dasharray="${r2(filled)} ${r2(arcLength)}"/>`
      : ''
  return `<svg viewBox="0 0 200 118" width="220" role="img" aria-label="${esc(label)}: ${Math.round(value)} out of 100">
    <path d="${arc}" fill="none" stroke="#30363d" stroke-width="14" stroke-linecap="round"/>
    ${valuePath}
    <text x="100" y="88" text-anchor="middle" font-size="34" font-weight="700" class="mono gauge-num">${Math.round(value)}</text>
    <text x="100" y="107" text-anchor="middle" fill="${band.color}" font-size="11" font-weight="600">${band.label}</text>
  </svg>
  <div class="gauge-label mono">${esc(label)}</div>`
}

export function renderLegend(): string {
  const bands: Array<{ range: string; label: string; color: string }> = [
    { range: '90–100', label: 'reliable', color: COLORS.ok },
    { range: '70–89', label: 'usable with caution', color: COLORS.warning },
    { range: '40–69', label: 'suspicious', color: COLORS.suspicious },
    { range: '<40', label: 'not fit for production', color: COLORS.critical },
  ]
  const items = bands
    .map(
      (b) =>
        `<li><span class="dot" style="background:${b.color}"></span><span class="mono">${esc(b.range)}</span> ${esc(b.label)}</li>`,
    )
    .join('')
  return `<ul class="legend">${items}</ul>`
}

export function renderSummaryChips(summary: Record<Severity, number>): string {
  const order: Severity[] = ['critical', 'warning', 'info']
  const chips = order
    .map((s) => `<span class="chip sev-${s}">${esc(summary[s] ?? 0)} ${s}</span>`)
    .join('\n')
  return `<div class="chips">${chips}</div>`
}

/**
 * Score explained: start at 100, subtract each finding's severity penalty
 * once (SEVERITY_PENALTY, the same table the scoring engine uses), clamped
 * at zero — the last row always equals the report's final score.
 */
export function renderPenaltyBreakdown(findings: Finding[]): string {
  if (findings.length === 0) {
    return '<div class="score-explained"><h3>How the score is built</h3><ol class="penalties"><li>start <span class="mono">100</span></li><li class="final">no penalties — final score <span class="mono">100</span></li></ol></div>'
  }
  let running = 100
  const rows = findings
    .map((finding) => {
      const penalty = SEVERITY_PENALTY[finding.severity]
      const before = running
      running = Math.max(0, running - penalty)
      return `<li><span class="mono rule">${esc(finding.rule)}</span> <span class="chip sev-${esc(finding.severity)}">${esc(finding.severity)}</span> <span class="mono pen">−${penalty}</span> <span class="dim mono">${before} → ${running}</span></li>`
    })
    .join('\n')
  return `<div class="score-explained"><h3>How the score is built</h3><ol class="penalties">
<li>start <span class="mono">100</span></li>
${rows}
<li class="final">final score <span class="mono">${running}</span></li>
</ol></div>`
}

/** Finding counts per DAMA-DMBOK quality dimension, all six always shown. */
export function renderDimensionChips(findings: Finding[]): string {
  const dimensions: QualityDimension[] = [
    'validity',
    'accuracy',
    'consistency',
    'completeness',
    'timeliness',
    'uniqueness',
  ]
  const counts = new Map<QualityDimension, number>()
  for (const finding of findings) {
    counts.set(finding.dimension, (counts.get(finding.dimension) ?? 0) + 1)
  }
  const chips = dimensions
    .map((dimension) => {
      const count = counts.get(dimension) ?? 0
      return `<span class="chip dim-chip${count === 0 ? ' zero' : ''}">${esc(dimension)} ${count}</span>`
    })
    .join('\n')
  return `<div class="dim-chips"><h3>DAMA dimensions</h3><div class="chips">${chips}</div></div>`
}

/** Only http(s) URLs may become links; anything else renders as inert text. */
function safeHref(url: string): string | null {
  return /^https?:\/\//i.test(url) ? url : null
}

function linkLabel(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return 'reference'
  }
}

function formatEvidenceValue(value: unknown): string {
  if (typeof value === 'string') return value
  try {
    const json = JSON.stringify(value)
    return json === undefined ? String(value) : json
  } catch {
    return String(value)
  }
}

function renderEvidence(evidence: Record<string, unknown> | undefined): string {
  if (!evidence || Object.keys(evidence).length === 0) return ''
  const items = Object.entries(evidence)
    .map(([key, value]) => `<dt>${esc(key)}</dt><dd class="mono">${esc(formatEvidenceValue(value))}</dd>`)
    .join('')
  return `<details class="evidence"><summary>evidence</summary><dl>${items}</dl></details>`
}

function renderReferences(references: string[] | undefined): string {
  if (!references || references.length === 0) return ''
  const links = references
    .map((ref) => {
      const href = safeHref(ref)
      if (href === null) return `<span class="mono">${esc(ref)}</span>`
      return `<a href="${esc(href)}" target="_blank" rel="noopener">${esc(linkLabel(href))}</a>`
    })
    .join('')
  return `<div class="refs">${links}</div>`
}

/**
 * Severity filter chips. Statically they double as finding counts; the
 * inline JS wires them to show/hide cards. Without JS the full list below
 * stays visible, so nothing is lost.
 */
export function renderFilterBar(findings: Finding[]): string {
  const counts: Record<Severity, number> = { critical: 0, warning: 0, info: 0 }
  for (const finding of findings) counts[finding.severity] += 1
  const chip = (filter: string, label: string, count: number, active: boolean): string =>
    `<button type="button" class="filter-chip${active ? ' active' : ''}" data-filter="${filter}">${esc(label)} ${count}</button>`
  return `<div class="filters" id="mdsc-filters"><span class="dim">filter:</span>
${chip('all', 'all', findings.length, true)}
${chip('critical', 'critical', counts.critical, false)}
${chip('warning', 'warning', counts.warning, false)}
${chip('info', 'info', counts.info, false)}
</div>`
}

/**
 * One card per finding, with an anchor id (finding-0, finding-1, …) so chart
 * markers can scroll to it. The action badge (block/flag/review) is the most
 * prominent element — what to do matters more than what fired.
 */
export function renderFindingCards(findings: Finding[]): string {
  return findings
    .map((finding, i) => {
      const where =
        finding.where && Object.keys(finding.where).length > 0
          ? `<div class="where mono">${Object.entries(finding.where)
              .map(([key, value]) => `${esc(key)}=${esc(value)}`)
              .join(' · ')}</div>`
          : ''
      const occurrences =
        finding.occurrences !== undefined && finding.occurrences > 1
          ? `<span class="chip occ">×${esc(finding.occurrences)}</span>`
          : ''
      return `<article class="finding-card" id="finding-${i}" data-severity="${esc(finding.severity)}">
  <div class="finding-head">
    <span class="action-badge act-${esc(finding.action)}">${esc(finding.action)}</span>
    <span class="chip sev-${esc(finding.severity)}">${esc(finding.severity)}</span>
    <span class="mono rule">${esc(finding.rule)}</span>
    <span class="chip dim-chip">${esc(finding.dimension)}</span>
    ${occurrences}
  </div>
  ${where}
  <p class="expl">${esc(finding.explanation)}</p>
  ${renderEvidence(finding.evidence)}${renderReferences(finding.references)}
</article>`
    })
    .join('\n')
}

export function metaItem(key: string, value: unknown): string {
  return `<div><div class="k">${esc(key)}</div><div class="mono">${esc(value)}</div></div>`
}

/** Uniform sampling that keeps both endpoints and the shape of long series. */
export function downsample<T>(items: readonly T[], max: number): T[] {
  if (items.length <= max) return [...items]
  const step = (items.length - 1) / (max - 1)
  const out: T[] = []
  for (let i = 0; i < max; i++) out.push(items[Math.round(i * step)]!)
  return out
}

/** Highest-severity finding per bar date, with the finding's index for anchor links. */
export interface DateMark {
  severity: Severity
  index: number
}

export function findingMarksByDate(findings: Finding[]): Map<string, DateMark> {
  const marks = new Map<string, DateMark>()
  findings.forEach((finding, index) => {
    const raw = finding.where?.['date']
    if (raw === undefined) return
    const date = String(raw).slice(0, 10)
    const prev = marks.get(date)
    if (prev === undefined || SEVERITY_RANK[finding.severity] > SEVERITY_RANK[prev.severity]) {
      marks.set(date, { severity: finding.severity, index })
    }
  })
  return marks
}

/**
 * Minimal, URL-free finding entries for the JSON payload. Explanations and
 * references are excluded on purpose: they are free text that may contain
 * URLs, and the "no http(s) outside hrefs" invariant must hold for the whole
 * file. The static cards already carry that prose; the JS only needs enough
 * to link chart markers to cards and drive filters.
 */
export interface PayloadFinding {
  i: number
  rule: string
  severity: Severity
  action: string
  date?: string
}

export function payloadFindings(findings: Finding[]): PayloadFinding[] {
  return findings.map((finding, i) => {
    const entry: PayloadFinding = {
      i,
      rule: finding.rule,
      severity: finding.severity,
      action: finding.action,
    }
    const date = finding.where?.['date']
    if (date !== undefined) entry.date = String(date).slice(0, 10)
    return entry
  })
}

/**
 * Serialize the #mdsc-data blob with every '<' escaped as its JSON unicode
 * escape — valid JSON (JSON.parse restores the character) but inert in
 * HTML, so no datum can ever produce a literal `</script>` and break out
 * of the blob.
 */
export function serializePayload(payload: unknown): string {
  return JSON.stringify(payload).replaceAll('<', '\\u003c')
}

/* ------------------------------------------------------------------ */
/* Chart geometry, shared by the check and compare charts so the       */
/* static SVG and the JS tooltip overlay always agree.                 */
/* ------------------------------------------------------------------ */

export const CHART = { width: 920, height: 320, padL: 64, padR: 16, padT: 14, padB: 30 } as const

export function xAt(i: number, n: number): number {
  return CHART.padL + (n <= 1 ? 0.5 : i / (n - 1)) * (CHART.width - CHART.padL - CHART.padR)
}

export function yAt(value: number, min: number, max: number): number {
  const span = max - min
  const t = span === 0 ? 0.5 : (value - min) / span
  return CHART.height - CHART.padB - t * (CHART.height - CHART.padT - CHART.padB)
}

/** Compact axis tick: adapt decimals to the magnitude of the value. */
export function formatTick(value: number): string {
  const abs = Math.abs(value)
  if (abs >= 1000) return value.toFixed(0)
  if (abs >= 1) return value.toFixed(2)
  return value.toPrecision(2)
}

/** Horizontal gridlines with price labels on the left axis. */
export function renderYGridlines(min: number, max: number, ticks = 5): string {
  const lines: string[] = []
  for (let k = 0; k < ticks; k++) {
    const value = ticks <= 1 ? min : min + ((max - min) * k) / (ticks - 1)
    const y = r2(yAt(value, min, max))
    lines.push(
      `<line class="grid" x1="${CHART.padL}" x2="${CHART.width - CHART.padR}" y1="${y}" y2="${y}"/>`,
      `<text class="tick" x="${CHART.padL - 8}" y="${r2(y + 4)}" text-anchor="end">${esc(formatTick(value))}</text>`,
    )
  }
  return lines.join('\n')
}

/** Date labels along the bottom axis, evenly spaced over the plotted points. */
export function renderXTicks(dates: string[], ticks = 6): string {
  const n = dates.length
  if (n === 0) return ''
  const count = Math.min(ticks, n)
  const labels: string[] = []
  for (let k = 0; k < count; k++) {
    const i = count <= 1 ? 0 : Math.round((k * (n - 1)) / (count - 1))
    labels.push(
      `<text class="tick" x="${r2(xAt(i, n))}" y="${CHART.height - CHART.padB + 20}" text-anchor="middle">${esc(dates[i] ?? '')}</text>`,
    )
  }
  return labels.join('\n')
}

/**
 * Transparent rect covering the plot area. Statically inert; the JS measures
 * it to map the mouse x position to the nearest plotted point for tooltips.
 */
export function renderHoverZone(): string {
  return `<rect id="mdsc-hover-zone" x="${CHART.padL}" y="${CHART.padT}" width="${CHART.width - CHART.padL - CHART.padR}" height="${CHART.height - CHART.padT - CHART.padB}" fill="#ffffff" fill-opacity="0"/>`
}

/** Assemble the final document: markup, JSON blob, enhancement script. */
export function page(title: string, body: string, payload: unknown): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${CSP}">
<title>${esc(title)}</title>
<style>
${CSS}
</style>
</head>
<body>
<main>
${body}
</main>
<script type="application/json" id="mdsc-data">${serializePayload(payload)}</script>
<script>
${ENHANCE_JS}
</script>
</body>
</html>
`
}

/**
 * The enhancement layer: fixed code, written once here, never built from
 * user data. It reads the #mdsc-data JSON blob and, when present:
 *  1. wires the severity filter chips to show/hide finding cards,
 *  2. makes chart markers (data-fi) scroll to their finding card,
 *  3. adds a hover tooltip to the price chart (OHLCV, or both closes and
 *     the % gap on compare pages).
 * Tooltip content is built with textContent only — blob data must never
 * become markup. Everything degrades silently when elements are missing.
 * Note: no URLs appear here; the self-containment test forbids http(s)
 * anywhere outside href attributes.
 */
const ENHANCE_JS = `
(function () {
  'use strict'
  var dataNode = document.getElementById('mdsc-data')
  if (!dataNode) return
  var data
  try {
    data = JSON.parse(dataNode.textContent || '{}')
  } catch (err) {
    return
  }

  var filters = document.getElementById('mdsc-filters')
  if (filters) {
    filters.addEventListener('click', function (ev) {
      var target = ev.target
      if (!target || !target.closest) return
      var btn = target.closest('[data-filter]')
      if (!btn) return
      var filter = btn.getAttribute('data-filter')
      var chips = filters.querySelectorAll('[data-filter]')
      for (var i = 0; i < chips.length; i++) chips[i].classList.toggle('active', chips[i] === btn)
      var cards = document.querySelectorAll('.finding-card')
      for (var j = 0; j < cards.length; j++) {
        var show = filter === 'all' || cards[j].getAttribute('data-severity') === filter
        cards[j].style.display = show ? '' : 'none'
      }
    })
  }

  function jumpTo(card) {
    card.scrollIntoView({ behavior: 'smooth', block: 'center' })
    card.classList.add('highlight')
    setTimeout(function () { card.classList.remove('highlight') }, 2400)
  }
  var markers = document.querySelectorAll('[data-fi]')
  for (var m = 0; m < markers.length; m++) {
    markers[m].style.cursor = 'pointer'
    markers[m].addEventListener('click', function () {
      var card = document.getElementById('finding-' + this.getAttribute('data-fi'))
      if (card) jumpTo(card)
    })
  }

  var svg = document.getElementById('mdsc-price-chart')
  var zone = document.getElementById('mdsc-hover-zone')
  var tip = document.getElementById('mdsc-tooltip')
  if (!svg || !zone || !tip) return
  var points = data.type === 'compare' ? data.points : data.bars
  if (!points || points.length === 0) return

  function fmt(v) {
    if (v === undefined || v === null || !isFinite(v)) return '—'
    return String(Math.round(v * 10000) / 10000)
  }

  function linesFor(p) {
    if (data.type === 'compare') {
      var denom = Math.max(p.a, p.b)
      var gap = denom > 0 ? (Math.abs(p.a - p.b) / denom) * 100 : 0
      return [
        p.d,
        data.sources[0] + ' close ' + fmt(p.a),
        data.sources[1] + ' close ' + fmt(p.b),
        'gap ' + gap.toFixed(2) + '%',
      ]
    }
    var lines = [p.d, 'O ' + fmt(p.o) + '  H ' + fmt(p.h), 'L ' + fmt(p.l) + '  C ' + fmt(p.c)]
    if (p.v !== undefined) lines.push('vol ' + fmt(p.v))
    return lines
  }

  svg.addEventListener('mousemove', function (ev) {
    var rect = zone.getBoundingClientRect()
    if (rect.width <= 0) return
    var frac = (ev.clientX - rect.left) / rect.width
    var idx = Math.round(frac * (points.length - 1))
    if (idx < 0) idx = 0
    if (idx >= points.length) idx = points.length - 1
    var lines = linesFor(points[idx])
    tip.textContent = ''
    for (var i = 0; i < lines.length; i++) {
      var div = document.createElement('div')
      div.textContent = lines[i]
      tip.appendChild(div)
    }
    tip.style.left = ev.clientX + 14 + 'px'
    tip.style.top = ev.clientY + 14 + 'px'
    tip.hidden = false
  })
  svg.addEventListener('mouseleave', function () {
    tip.hidden = true
  })
})()
`

/**
 * Dark financial-terminal theme on a system font stack. No external fonts,
 * no URLs. Print media query keeps the report legible on paper.
 */
const CSS = `
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body {
  margin: 0;
  background: #0d1117;
  color: #e6edf3;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.5;
}
main { max-width: 960px; margin: 0 auto; padding: 24px 16px 48px; }
a { color: #58a6ff; }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; }
.dim { color: #8b949e; font-weight: 400; }
.card {
  background: #161b22;
  border: 1px solid #30363d;
  border-radius: 8px;
  padding: 16px 20px;
  margin: 0 0 16px;
}
h1 { font-size: 1.35rem; margin: 0 0 12px; }
h2 {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #8b949e;
  margin: 0 0 12px;
}
h3 {
  font-size: 0.7rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #8b949e;
  margin: 16px 0 8px;
}
.meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 10px; }
.k { color: #8b949e; font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.06em; }
.repo-link { margin-top: 12px; font-size: 0.8rem; }
.gauge-wrap { display: flex; align-items: center; gap: 32px; flex-wrap: wrap; }
.gauge { text-align: center; }
.gauge-num { fill: #e6edf3; }
.gauge-label { color: #8b949e; font-size: 0.75rem; margin-top: 4px; }
.legend { list-style: none; margin: 0; padding: 0; font-size: 0.85rem; }
.legend li { display: flex; align-items: center; gap: 8px; margin: 4px 0; }
.dot { width: 10px; height: 10px; border-radius: 50%; flex: none; }
.chips { display: flex; gap: 8px; flex-wrap: wrap; align-content: center; }
.chip {
  display: inline-block;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
  border: 1px solid;
  white-space: nowrap;
}
.sev-critical { color: #f85149; border-color: #f85149; background: rgba(248, 81, 73, 0.12); }
.sev-warning { color: #d29922; border-color: #d29922; background: rgba(210, 153, 34, 0.12); }
.sev-info { color: #58a6ff; border-color: #58a6ff; background: rgba(88, 166, 255, 0.12); }
.chip.occ { color: #e6edf3; border-color: #30363d; background: #21262d; }
.dim-chip { color: #c9d1d9; border-color: #30363d; background: #21262d; text-transform: none; }
.dim-chip.zero { opacity: 0.45; }
.penalties { list-style: none; margin: 0; padding: 0; font-size: 0.85rem; }
.penalties li { padding: 3px 0; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.penalties .pen { color: #f85149; font-weight: 700; }
.penalties .final { border-top: 1px solid #30363d; margin-top: 4px; padding-top: 8px; font-weight: 600; }
.filters { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin: 0 0 14px; }
.filter-chip {
  font: inherit;
  font-size: 0.75rem;
  font-weight: 600;
  color: #8b949e;
  background: #21262d;
  border: 1px solid #30363d;
  border-radius: 999px;
  padding: 2px 12px;
  cursor: pointer;
}
.filter-chip.active { color: #e6edf3; border-color: #58a6ff; background: rgba(88, 166, 255, 0.12); }
.finding-cards { display: grid; gap: 12px; }
.finding-card {
  border: 1px solid #30363d;
  border-left-width: 3px;
  border-radius: 6px;
  padding: 12px 16px;
  background: #0d1117;
}
.finding-card[data-severity="critical"] { border-left-color: #f85149; }
.finding-card[data-severity="warning"] { border-left-color: #d29922; }
.finding-card[data-severity="info"] { border-left-color: #58a6ff; }
.finding-card.highlight { outline: 2px solid #58a6ff; box-shadow: 0 0 12px rgba(88, 166, 255, 0.35); }
.finding-head { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.action-badge {
  display: inline-block;
  padding: 2px 12px;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}
.act-block { color: #ffffff; background: #f85149; }
.act-flag { color: #0d1117; background: #d29922; }
.act-review { color: #0d1117; background: #58a6ff; }
.rule { font-weight: 600; }
.where { font-size: 0.78rem; color: #8b949e; word-break: break-word; margin-top: 6px; }
.expl { word-break: break-word; margin: 8px 0 0; font-size: 0.9rem; }
details { margin-top: 6px; }
summary { cursor: pointer; color: #8b949e; font-size: 0.75rem; }
dl { display: grid; grid-template-columns: max-content 1fr; gap: 2px 12px; margin: 6px 0 0; font-size: 0.78rem; }
dt { color: #8b949e; }
dd { margin: 0; word-break: break-word; }
.refs { margin-top: 6px; display: flex; gap: 12px; flex-wrap: wrap; font-size: 0.78rem; }
.chart { width: 100%; height: auto; display: block; }
.grid { stroke: #21262d; stroke-width: 1; }
.tick { fill: #8b949e; font-size: 11px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; }
.tooltip {
  position: fixed;
  z-index: 10;
  background: #1c2128;
  border: 1px solid #444c56;
  border-radius: 6px;
  padding: 6px 10px;
  font-size: 0.78rem;
  pointer-events: none;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.5);
}
.overlay-legend { margin-top: 10px; }
.clean { color: #3fb950; font-weight: 600; margin: 0; }
.stats { display: flex; gap: 32px; flex-wrap: wrap; margin-top: 16px; }
.stat-v { font-size: 1.4rem; font-weight: 700; }
footer { color: #8b949e; font-size: 0.75rem; text-align: center; margin-top: 32px; }
@media print {
  body { background: #ffffff; color: #111111; }
  .card { background: #ffffff; border-color: #cccccc; break-inside: avoid; }
  a { color: #0b419a; }
  h2, h3, .k, summary, dt, .where, .dim, footer, .gauge-label { color: #444444; }
  .gauge-num { fill: #111111; }
  .tick { fill: #444444; }
  .grid { stroke: #dddddd; }
  .chip.occ, .dim-chip { color: #111111; border-color: #cccccc; background: #f0f0f0; }
  .filter-chip, .filters, .tooltip { display: none; }
  .finding-card { background: #ffffff; break-inside: avoid; }
  .finding-card.highlight { outline: none; box-shadow: none; }
  .penalties .final { border-color: #cccccc; }
}
`
